### PR TITLE
Export S1B-D benchmarking data TSVs

### LINKED ISSUE #216: Add lines to export benchmarking TSVs
Broken out of #204 following this comment: https://github.com/AlexsLemonade/scpca-paper-figures/issues/204#issuecomment-2733499070

This issue tracks adding lines to `scripts/FigS1B-D_method-metrics-comparison.R` to export TSVs of data underlying the figures. Following some discussion, we do not plan to write a separate script here which would split up generating these TSVs and making the figures, and our goal will just be to make the underlying data available.

Here are the data frames we'll want to export, based what's passed into ggplot:

- `rowdata_cor`, which is used for panel S1B
https://github.com/AlexsLemonade/scpca-paper-figures/blob/55f597054610de828b79705f136f742d40ba1985/scripts/FigS1B-D_method-metrics-comparison.R#L209

- `coldata_common`, which is used for panels S1C and S1D
https://github.com/AlexsLemonade/scpca-paper-figures/blob/55f597054610de828b79705f136f742d40ba1985/scripts/FigS1B-D_method-metrics-comparison.R#L154

An open question is where to save these files in the repo (assuming they are small enough for GitHub - I assume they will be but if not we might have to export sample-specific TSV files). My thoughts are...
- We do store some data in `sample-info`, but I don't think this data really counts as sample info to store there. 
- We could store them in `nextflow_logs` which is already storing some benchmark-related data, though these are definitely not logs
- Create a new directory to hold these files; We are going to at least two more Zenodo-upload--related files to add to the repo, as outlined in #211 & #212, so maybe we put all of this in the same spot.

### PR DESCRIPTION
**Pull request by sjspielman**
Closes #216 

This PR adds code to the `FigS1B-D_method-metrics-comparison.R` script to export TSV files needed to remake figures to assist in reproducibility. TSVs are exported to a new directory `reproduce-figures-analysis`, which is also being populated in other PRs (#217, #224 for now) - because this directory is subhect to change and I want to reduce conflicts here, I haven't yet documented these files. I do plan to open a future issue to solidify this directory later though.

**Notably** it was quick to add an `if` statement to control which aprts of the script to run, so I went ahead and did it. But, this was all in one commit (https://github.com/AlexsLemonade/scpca-paper-figures/commit/cc4fa9da11c6c7704a9db4daec24b29315582da5) and can be reverted for just a simple TSV export.

### CODE REVIEW

**Comment by sjspielman** [comment]
@allyhawkins since you've been reviewing some of these types of PRs already, I'm going to request you for this one too if that's cool! Let me know how I can clarify anything here and if you have other ideas for accomplishing this. 

One of the things this PR does is export files to a new folder called `reproduce-figures-analysis`, which I've set up in some other PRs indicated in the opening comment here to hold these types of files. I very much welcome feedback on that directory name and any associated organization, but note that some of that may come in later PRs as that directory fills up a bit more. We will definitely want to add something to the overall README about it as well if we keep this general organization. 

Because some of this might still be subject to discussion, you can certainly wait to review (or at least approve) until after next planning meeting!

**Comment by sjspielman** [comment]
Backing up; let's do #237 first and then will un-draft.

File: scripts/FigS1B-D_method-metrics-comparison.R [hunk 1]
```diff
@@ -64,69 +64,13 @@ umi_pdf_file <- file.path(pdf_dir, "FigS1C-umi-benchmarking.pdf")
...
-    \(quant_dir){
-      sce <- scpcaTools::read_alevin(
-        quant_dir = quant_dir,
-        fry_mode = TRUE) |> 
-        # filter empty droplets 
-        scpcaTools::filter_counts()
-    }
-  )
+# output TSV files of figure data
+repro_dir <- here::here("reproduce-figures-analysis")
```
Comment (allyhawkins) [inline scripts/FigS1B-D_method-metrics-comparison.R:68]:
```suggestion
repro_dir <- here::here("reproduce-figures")
```

**Review by allyhawkins — APPROVED** [review]
LGTM

**Comment by sjspielman** [comment]
Came here to mark as ready for review, and what a fun surprise it's approved 🚀 !
